# Generated by Django 4.1.4 on 2023-03-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('fimg', models.ImageField(upload_to='pics')),
                ('fdesc', models.TextField()),
            ],
        ),
    ]
